sonar.projectKey=bartsam_OC-P5-Full-stack
sonar.organization=bartsam
sonar.sourceEncoding=UTF-8

sonar.sources=front/src,back/src/main/java
sonar.tests=front/src,back/src/test/java
sonar.test.inclusions=front/src/**/*.spec.ts,front/src/**/*.int.spec.ts,back/src/test/java/**/*.java
sonar.exclusions=front/src/**/*.spec.ts,front/src/**/*.int.spec.ts,front/src/test.ts

sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=front/coverage/vitest/lcov.info
